-- Tabela: Pipes
CREATE TABLE IF NOT EXISTS pipes (
    "Codigo" TEXT PRIMARY KEY,
    "Nome" TEXT,
    "Empresa" TEXT
);

-- Tabela: Corretores
CREATE TABLE IF NOT EXISTS corretores (
    "Codigo" TEXT PRIMARY KEY,
    "Nome" TEXT
);

-- Tabela: Agencias
CREATE TABLE IF NOT EXISTS agencias (
    "Codigo" TEXT PRIMARY KEY,
    "Nome" TEXT,
    "Empresa" TEXT,
    "Responsavel" TEXT,
    "Endereco" TEXT,
    "Bairro" TEXT,
    "Cidade" TEXT,
    "Cep" TEXT,
    "Uf" TEXT,
    "Pais" TEXT,
    "Fone" TEXT,
    "E-mail" TEXT,
    "Numero" TEXT,
    "Complemento" TEXT,
    "CodigoEmpresa" TEXT,
    "Ddd" TEXT,
    "Cnpj" TEXT,
    "Cpf" TEXT,
    "RazaoSocial" TEXT,
    "Fone2" TEXT,
    "Celular" TEXT,
    "Creci" TEXT,
    "Site" TEXT
);

-- Tabela: Usuarios
CREATE TABLE IF NOT EXISTS usuarios (
    "Codigo" TEXT PRIMARY KEY,
    "Nome" TEXT,
    "Email" TEXT,
    "Datacadastro" TEXT,
    "RGInscricao" TEXT,
    "RGEmissor" TEXT,
    "CPFCGC" TEXT,
    "Nascimento" TEXT,
    "Nacionalidade" TEXT,
    "CNH" TEXT,
    "CNHExpedicao" TEXT,
    "CNHVencimento" TEXT,
    "Celular" TEXT,
    "Endereco" TEXT,
    "Bairro" TEXT,
    "Cidade" TEXT,
    "UF" TEXT,
    "CEP" TEXT,
    "Pais" TEXT,
    "Fone" TEXT,
    "Fax" TEXT,
    "E-mail" TEXT,
    "Observacoes" TEXT,
    "Administrativo" TEXT,
    "Agenciador" TEXT,
    "Gerente" TEXT,
    "Empresa" TEXT,
    "Celular1" TEXT,
    "Celular2" TEXT,
    "Corretor" TEXT,
    "Datasaida" TEXT,
    "Grupoacesso" TEXT,
    "Nomecompleto" TEXT,
    "Ramal" TEXT,
    "Sexo" TEXT,
    "Exibirnosite" TEXT,
    "RecebeClientesemTrocaautomática" TEXT,
    "Inativo" TEXT,
    "CRECI" TEXT,
    "Estadocivil" TEXT,
    "Diretor" TEXT,
    "MetadeCaptacoes" TEXT,
    "MetaValordeVendas" TEXT,
    "EnderecoTipo" TEXT,
    "EnderecoNumero" TEXT,
    "EnderecoComplemento" TEXT,
    "Bloco" TEXT,
    "Chat" TEXT,
    "CategoriaRanking" TEXT,
    "Atuaçãoemvenda" TEXT,
    "Atuaçãoemlocação" TEXT,
    "DataUltimoLogin" TEXT,
    "CodigoAgencia" TEXT,
    "Foto" TEXT
);

-- Tabela: Proprietarios
CREATE TABLE IF NOT EXISTS proprietarios (
    "Codigo" TEXT PRIMARY KEY,
    "Nome" TEXT,
    "FotoCliente" TEXT,
    "Foto" TEXT,
    "CodigoAgencia" TEXT,
    "Corretor" TEXT,
    "Agencia" TEXT,
    "CPFCNPJ" TEXT,
    "CreditoSituacao" TEXT,
    "CreditoMensagem" TEXT,
    "CODIGO_CREDPAGO" TEXT,
    "PossuiAnexo" TEXT,
    "AnexoCodigoFinalidade" TEXT
);

-- Tabela: Clientes
CREATE TABLE IF NOT EXISTS clientes (
    "Codigo" TEXT PRIMARY KEY,
    "Nome" TEXT,
    "CPFCNPJ" TEXT,
    "RG" TEXT,
    "DataNascimento" TEXT,
    "Sexo" TEXT,
    "EstadoCivil" TEXT,
    "Profissao" TEXT,
    "Nacionalidade" TEXT,
    "EmailResidencial" TEXT,
    "FonePrincipal" TEXT,
    "Celular" TEXT,
    "FoneComercial" TEXT,
    "EmailComercial" TEXT,
    "EnderecoResidencial" TEXT,
    "EnderecoNumero" TEXT,
    "EnderecoComplemento" TEXT,
    "BairroResidencial" TEXT,
    "CidadeResidencial" TEXT,
    "UFResidencial" TEXT,
    "CEPResidencial" TEXT,
    "Status" TEXT,
    "DataCadastro" TEXT,
    "DataAtualizacao" TEXT,
    "Observacoes" TEXT
);

-- Tabela: Negocios
CREATE TABLE IF NOT EXISTS negocios (
    "Codigo" TEXT PRIMARY KEY,
    "Titulo" TEXT,
    "ValorVenda" NUMERIC,
    "ValorLocacao" NUMERIC,
    "Fase" TEXT,
    "DataCadastro" TIMESTAMP,
    "DataAtualizacao" TIMESTAMP,
    "DataFechamento" TIMESTAMP,
    "Status" TEXT,
    "CodigoCliente" TEXT,
    "CodigoCorretor" TEXT,
    "CodigoAgencia" TEXT,
    "Origem" TEXT,
    "Midia" TEXT,
    "Observacao" TEXT,
    "ObservacaoPerda" TEXT,
    "NomeCliente" TEXT,
    "NomeCorretor" TEXT,
    "NomeAgencia" TEXT,
    "MotivoPerda" TEXT,
    "DataPerda" TIMESTAMP,
    "DataGanho" TIMESTAMP,
    "PipeID" TEXT,
    "PipeNome" TEXT
);


-- Tabela: Atividades
CREATE TABLE IF NOT EXISTS atividades (
    "CodigoAtividade" TEXT PRIMARY KEY,
    "CodigoNegocio" TEXT,
    "CodigoImovel" TEXT,
    "ValorProposta" NUMERIC,
    "EstadoProposta" TEXT,
    "TextoProposta" TEXT,
    "Aceitacao" TEXT,
    "Automatico" TEXT,
    "Numero" TEXT,
    "Texto" TEXT,
    "Pendente" TEXT,
    "Assunto" TEXT,
    "EtapaAcaoId" TEXT,
    "EtapaAcao" TEXT,
    "TipoAtividade" TEXT,
    "TipoAtividadeId" TEXT,
    "MotivoLost" TEXT,
    "CodigoEmImovel" TEXT,
    "Hora" TEXT,
    "AtividadeCreatedAt" TIMESTAMP,
    "AtividadeUpdatedAt" TIMESTAMP,
    "Data" TIMESTAMP,
    "CodigoCliente" TEXT,
    "CodigoCorretor" TEXT,
    "NumeroAgenda" TEXT,
    "DataHora" TIMESTAMP,
    "DataAtualizacao" TIMESTAMP,
    "Local" TEXT,
    "Inicio" TEXT,
    "Final" TEXT,
    "Prioridade" TEXT,
    "Privado" TEXT,
    "AlertaMinutos" TEXT,
    "Excluido" TEXT,
    "Concluido" TEXT,
    "Tarefa" TEXT,
    "DataConclusao" TIMESTAMP,
    "DiaInteiro" TEXT,
    "TipoAgenda" TEXT,
    "CodigoDev" TEXT,
    "IdGoogleCalendar" TEXT,
    "StatusVisita" TEXT,
    "CodigoImobiliaria" TEXT,
    "Icone" TEXT,
    "Duracao" TEXT,
    "FotoCorretor" TEXT,
    "Status" TEXT
);
